export const CHANGE_HOT_KEYWORDS = 'search/CHANGE_HOT_KEYWORDS'
export const CHANGE_SUGGEST_LIST = 'search/CHANGE_SUGGEST_LIST'
export const CHANGE_SONGS_LIST = 'search/CHANGE_SONGS_LIST'
export const CHANGE_ENTER_LOADING = 'search/CHANGE_ENTER_LOADING'